[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.28"
once_cell = "1.21.3"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
