name: server test

on:
  push:
    paths:
      - 'server/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd server
      run: cd server
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
